* Ejecutamos una aplicación en un móvil.

  En nuestro Android móvil, instalamos 'Expo Project' app desde
  Android 'Play' tienda. 

  Usando el 'Snack Player' herramienta can contiene el código de
  ejemplo 'Hello Mundo' que hemos editado. Generamos un QR código.

  En el 'Expo Project' app puedes scaniar este código para transferir
  nuestro código a nuestro móvil.

  ¡Lo funcionó!

  #+BEGIN_EXPORT html
  <div class="article-entry-date"><span class="article-entry-date">2022.02.01 15:59</span></div>
  #+END_EXPORT

* Creamos nuestra primera applicación.    

  Visitamos [[https://reactnative.dev][la página web oficial de React Native]]. Y fuimos
  directamente al artículo [[https://reactnative.dev/docs/getting-started][Getting Started]].
  
  Allí puedes usar un herramienta integrado en la página web, llamado
  'Snack Player' para escribir código en React Native y ver los
  resultados. 

  Cambiamos el texto en el ejemplo 'Hello World' desde 'Try editing
  me!' a 'Hola Saki'. Puedes ver sus cambios renderizados en tiempo
  real. ¡Qué guay!

  #+BEGIN_EXPORT html
  <div class="article-entry-date"><span class="article-entry-date">2022.02.01 15:56</span></div>
  #+END_EXPORT
