* equivocaciones de deletreo/ortográficos

   se +confonde+ *confunde*

* debajo vs bajo

   Él tiene un tatuaje de una lágrima +bajo+ *debajo* de su ojo.


* matrices de palabras.
** conocer vs saber

   Yo conozco las adivinanzas pero no sé ninguna.
   Yo conozco las adivinanzas pero solo me sé algunas.
   
* alguna vs ninguno

     Yo conozco las adivinanzas pero no sé +alguna+ ninguna.
     Yo conozco las adivinanzas pero solo me sé algunas. 

     positivo con positivo - sé alguna
     negativo con negativo - no sé ninguna
* adivinanzas

  oro parece,
  plata no es, 
  quién no la adivine,
  bien tonto es. 
  ¿Qué es?

  respuesta: platano

  ¿Cuál es el animal que
  camina con 4 cuatro patas en su niñez,
  dos patas en su joventud
  y tres patas en su vejez?

  respuesta: humano

  De la sala a la cocina y mueve la cola como una gallina.
 
  la escoba  - the broom  

  


* https://albalearning.com/audiolibros/chopin/unamujer.html 
* https://albalearning.com/audiolibros/quiroga/elalmohadon.html 
