* 3 Sep 2021
** aves rapaces - birds of prey
** juicioso/a - wisdom

   Ella era juiciosa - she was wise

   juicioso - tiene juicio

   Qué niño tan juicioso que hace toda su tarea.
** cortinero - curtain rod

     ¿Qué es un cortinero? - Lo que sostiene la cortina.

** estaño - tin

  aniversario de estaño
** encaje - lace
** marfil - ivy

  el marfil de los colmillos de los elefantes se emplea para fabricar
  esculturas. 
** comillo - fang/tusk

   el marfil de los colmillos de los elefantes se emplea para fabricar
  esculturas. 
** tequeño - tipo de comida venezolano

    tequeño con guascana 
** pararse - stop / standup

   pararse para levantarse - stand up to get up

   comí hasta que paró el ombligo - I ate until my belly button
** copo(s) de nieve - snowflake

   Mi lavadora tiene un símbulo de 'copo de nieves' para la temperatura.
** brincar - to jump

   El gato brincó a la mesa

  sinomino: saltar
** juego de cama - bedding

    Cambié todo el juego de cama
** colchón - mattress

     un protector de colchón
** ganzo - goose

   el almohada es de ganzo.

** edredón 

    Un edredón es grueso. Puede tener un relleno de plumas o algodón.
** antialérgico - antiallergic

    El edredón es antialérgico
    Una almohada antialégica

** estremeciento - to shudder

  colmado/a de emociones - full of emoción (positiva o negativa)
** picar - to sting

   Durant el safari le picó una víbora (viper).
** rascar - to scratch

   David se rasca la cabeza. 

** cafetera

   Meli quiere una nueva cafetera - Meli wants a new coffee machine
** cafetería



   Una cafetería puede generar plata.
** rara

   ella estaba rara - she felt strange/weir/unwell/not herself
** pica
* 2 Sep 2021
**  derretirse - to melt

  El chocolate se derrite en su país más rápido que en nuestro país.
** arrojar - to throw

   Me gusta arrojar la pelota con mi perro.
   error: a dog can not throw a ball
   I like to throw the ball with my dog (in a team, throwing together
   a something)

   Me gusta arrojarle la pelota a mi perro.
   I like to throw the ball to my dog. 
** estante - shelf

   Se puede poner libros en un estante.
** destinatario/a - recipient

    El objeto indirecto es la persona (y con menos frecuencia, la
    cosa) destinatario final de la acción del verbo.
** fiar - trust/guarantee/confiance/loan

       hoy no se fia, venga mañana
** arrendatario - landlord
  
   Ayer mi arrendatario dijo que quería subir la renta porque ahora hay
   menos personas viviendo en la casa.
** magacín/magazín 

    Un magacín es un tipo de programa en televisión, o publicación periódica,
    que muestra reportajes, entrevistas, y actualizaciones artísticas.
    Es realizado con regularidad.
** informativo  

    Un informativo es un tipo de programa en televisión que muesta las noticias
** pañuelo - handkerchief

   Cuando yo era chico, mi abuela siempre me compraba pañuelos para la
   navidad. 
** mamitero/mamitis - chico mamá - mummies boy

    El chico en la película era un mamitero (una palabra de Meli).
 
** alcoholímetro - breathalyzer

    Él tiene que +tomar+ *utilizar* el alcoholímetro.
    Él tiene que tomar una prueba de alcohol.
** tararear - to hum

    Me reí porque Meli estaba tarareando felizmente.
** voltearse - turn around

     se volteó - he turned his back.
** puño - fist
** enpuñados - make a fist/grasp

   Enpuño las manos para golpearlo - He clenched the fists in order to
   hit him. 

   Tenía las manos empuñados. - He had his fists clenched.


** empuñar - wield/grasp/grip/clutch/clench
** chingar - fuck
** adivinar - to guess

    ¿puedes adivinar esto? - Can you guess this?
** adivinazas - riddle

    Me sé algunas adivinanzas - I know some riddles?

** rabo - tail

      Un rabo es la misa cosa de la cola.
** liendres - nits 
    Los chicos pillan liendres en las escuelas.
** piojos - lice

    A los chicos les pegan piojos en la escuela.

    uno son los hijos de los otros - piojos, liendres
** chupapollas/chupapija/mamahuevo/chupapito - cock sucker

     Ese chupapito ha derramado mi bebida

** derramar - to spill

     Ese chupapito ha derramado mi bebida
** sorbete - sorbet
 
    Entre los platos recibimos un pitillo para limpiar el paladar.

** paja/pitillo - straw
** una morena - a brunette o dark skin woman

* 1 sep 2021
 
** atorar - to jam
** atorado - stuck
  
   El papel está atorado.

** oponer - to oppose
  
   El padre se opone a su relación con Tomás.

** tallo - stem

  La flor tiene tallo, hojas y, a veces, espinas.

  Quité unas hojas del tallo.

** hojas - leaves

  La flor tiene tallo, hojas y, a veces, espinas.

  Quité unas hojas del tallo.

** espinas - thornes
  
   La flor tiene tallo, hojas y, a veces, espinas.

